include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = Little16Prefs
Little16Prefs_FILES = RootListController.m
Little16Prefs_INSTALL_PATH = /Library/PreferenceBundles
Little16Prefs_FRAMEWORKS = UIKit
Little16Prefs_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk